# -*- coding: utf-8 -*-
"""sales-analysis-project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAMYQeH7bSt1ISCgDUGryU3AHW72IGPy
"""

!git clone https://github.com/KeithGalli/Pandas-Data-Science-Tasks.git

import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

path = "/content/Pandas-Data-Science-Tasks/SalesAnalysis/Sales_Data"

files = [file for file in os.listdir(path)]

all_data = pd.DataFrame()

for file in files:
    df = pd.read_csv(path + "/" + file)
    all_data = pd.concat([all_data, df])

all_data.head()

# Remove nulls
all_data = all_data.dropna()

# Remove invalid rows
all_data = all_data[all_data['Order Date'].str[0:2] != 'Or']

# Convert types
all_data['Quantity Ordered'] = pd.to_numeric(all_data['Quantity Ordered'])
all_data['Price Each'] = pd.to_numeric(all_data['Price Each'])

# Create Sales column
all_data['Sales'] = all_data['Quantity Ordered'] * all_data['Price Each']

# Convert date
all_data['Order Date'] = pd.to_datetime(all_data['Order Date'])

# Extract features
all_data['Month'] = all_data['Order Date'].dt.month
all_data['Hour'] = all_data['Order Date'].dt.hour
all_data['Minute'] = all_data['Order Date'].dt.minute
all_data['Day'] = all_data['Order Date'].dt.dayofweek

# Extract City + State
def get_city(address):
    return address.split(",")[1] + " (" + address.split(",")[2].split(" ")[1] + ")"

all_data['City'] = all_data['Purchase Address'].apply(get_city)

print("🔹 Monthly Sales:\n")
print(all_data.groupby('Month')['Sales'].sum().sort_values(ascending=False))

print("\n🔹 Sales by City:\n")
print(all_data.groupby('City')['Sales'].sum().sort_values(ascending=False))

print("\n🔹 Best Selling Products:\n")
print(all_data.groupby('Product')['Quantity Ordered'].sum().sort_values(ascending=False))

print("\n🔹 Average Price per Product:\n")
print(all_data.groupby('Product')['Price Each'].mean().sort_values(ascending=False))

monthly_sales = all_data.groupby('Month')['Sales'].sum()

plt.figure(figsize=(8,5))
plt.bar(range(1,13), monthly_sales)

plt.xlabel("Month")
plt.ylabel("Sales")
plt.title("Monthly Sales Analysis")

plt.show()

plt.figure(figsize=(8,5))

plt.scatter(all_data['Quantity Ordered'], all_data['Price Each'])

plt.xlabel("Quantity Ordered")
plt.ylabel("Price Each")
plt.title("Quantity vs Price")

plt.show()

city_sales = all_data.groupby('City')['Sales'].sum()
cities = [city for city, df in all_data.groupby('City')]

plt.figure(figsize=(10,5))

plt.bar(cities, city_sales)
plt.xticks(rotation='vertical')

plt.xlabel("City")
plt.ylabel("Sales")
plt.title("Sales by City")

plt.show()

product_group = all_data.groupby('Product')
quantity_ordered = product_group['Quantity Ordered'].sum()

products = [product for product, df in product_group]

plt.figure(figsize=(10,5))

plt.bar(products, quantity_ordered)
plt.xticks(products, rotation='vertical', size=8)

plt.xlabel("Product")
plt.ylabel("Quantity Ordered")
plt.title("Best Selling Products")

plt.show()

product_revenue = all_data.groupby('Product')['Sales'].sum().sort_values()

# Horizontal bar
plt.figure(figsize=(10,6))
plt.barh(product_revenue.index, product_revenue.values)

plt.xlabel("Revenue")
plt.ylabel("Product")
plt.title("Product Revenue")

plt.show()

# Seaborn styled
plt.figure(figsize=(10,6))
sns.barplot(x=product_revenue.values, y=product_revenue.index)

plt.title("Product Revenue (Seaborn Style)")
plt.show()

hours = [hour for hour, df in all_data.groupby('Hour')]
orders_per_hour = all_data.groupby('Hour').count()

plt.figure(figsize=(10,5))

plt.fill_between(hours, orders_per_hour['Order ID'], alpha=0.5)
plt.plot(hours, orders_per_hour['Order ID'])

plt.axvline(x=11, color='r', linestyle='--')
plt.axvline(x=19, color='r', linestyle='--')

plt.xlabel("Hour")
plt.ylabel("Orders")
plt.title("Best Time for Ads")

plt.grid()
plt.show()

df = all_data[all_data['Order ID'].duplicated(keep=False)]

df['Grouped'] = df.groupby('Order ID')['Product'].transform(lambda x: ','.join(x))
df = df[['Order ID', 'Grouped']].drop_duplicates()

from itertools import combinations
from collections import Counter

count = Counter()

for row in df['Grouped']:
    row_list = row.split(',')
    count.update(Counter(combinations(row_list, 2)))

print(count.most_common(10))

plt.figure(figsize=(8,5))

sns.heatmap(all_data[['Quantity Ordered','Price Each','Sales','Hour']].corr(),
            annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()